# Use Docker-based container (instead of OpenVZ)
sudo: false

language: scala

scala:
  - 2.11.8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

# Q: should we use sbt ++$TRAVIS_SCALA_VERSION test?

after_success:
  - "[[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master'* ]]

script:
  - sbt clean
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm